Repository heroku/buildpacks-go, pull requests merged in 2024-04, with the labels that each got.

#251 Reintroduce stacks into buildpack.toml for compatibility with pack
  buildpacks/go/buildpack.toml
Labels: skip changelog

#253 Add Darwin to Os enum
  common/inventory-utils/src/inv.rs
Labels: rust, skip changelog

#252 Use OCI compliant arch ids
  buildpacks/go/inventory.toml
  buildpacks/go/src/tgz.rs
  buildpacks/go/tests/integration_test.rs
  common/go-utils/src/inv.rs
  common/inventory-utils/src/inv.rs
Labels: rust, skip changelog

#254 Remove Version marker trait
  common/go-utils/src/vrs.rs
  common/inventory-utils/Cargo.toml
  common/inventory-utils/src/inv.rs
Labels: enhancement, rust, skip changelog

#256 Merge inventory utils
  .github/workflows/inventory.yml
  common/go-utils/src/bin/diff_inventory.rs
  common/go-utils/src/bin/update_inventory.rs
Labels: rust, skip changelog
