Repository heroku/buildpacks-go, pull requests merged in 2024-03, with the labels that each got.

#222 Enable `unused_crate_dependencies` lint
  Cargo.lock
  Cargo.toml
  buildpacks/go/Cargo.toml
  buildpacks/go/src/main.rs
  buildpacks/go/tests/integration_test.rs
  common/go-utils/src/bin/diff_inventory.rs
  common/go-utils/src/bin/update_inventory.rs
Labels: skip changelog

#223 Add CONTRIBUTING.md guide
  CONTRIBUTING.md
  README.md
Labels: skip changelog

#225 Rename `LICENSE.txt` to `LICENSE`
  LICENSE
  README.md
Labels: skip changelog

#224 Fix readme link syntax
  CONTRIBUTING.md
  README.md
Labels: documentation, skip changelog

#226 Update README.md to Heroku Cloud Native Buildpacks guideline
  README.md
Labels: skip changelog

#231 Implement buildpack API 0.10
  Cargo.lock
  buildpacks/go/CHANGELOG.md
  buildpacks/go/Cargo.toml
  buildpacks/go/buildpack.toml
  buildpacks/go/src/layers/build.rs
  buildpacks/go/src/layers/deps.rs
  buildpacks/go/src/layers/dist.rs
  buildpacks/go/src/layers/target.rs
Labels: dependencies, rust

#229 Refactor artifact architecture and url
  buildpacks/go/inventory.toml
  buildpacks/go/src/layers/dist.rs
  common/go-utils/src/inv.rs
Labels: skip changelog

#230 Add inventory support for arm64 linux artifacts
  buildpacks/go/CHANGELOG.md
  buildpacks/go/inventory.toml
  common/go-utils/src/bin/diff_inventory.rs
  common/go-utils/src/bin/update_inventory.rs
  common/go-utils/src/inv.rs
Labels: enhancement, rust

#235 Require serde derive feature
  common/go-utils/Cargo.toml
Labels: bug, skip changelog

#236 Update readme
  README.md
Labels: documentation, skip changelog

#237 Prefer artifact over version in buildpack layers
  buildpacks/go/src/layers/build.rs
  buildpacks/go/src/layers/dist.rs
  buildpacks/go/src/main.rs
  buildpacks/go/tests/integration_test.rs
Labels: rust, skip changelog

#238 Rename Artifact go_version to version
  buildpacks/go/inventory.toml
  common/go-utils/src/inv.rs
Labels: rust, skip changelog

#233 Support arm64
  buildpacks/go/CHANGELOG.md
  buildpacks/go/buildpack.toml
Labels: enhancement, rust
